language: objective-c

branches:
 only:
 - develop

xcode_project: CISum.xcodeproj  #can also use xcode_workspace
xcode_scheme: CISumTests        #test scheme
osx_image: xcode8.3.2
xcode_sdk: iphonesimulator10.3

####Develop branch build status:
![](https://github.com/lnguyenviseo/cisum.svg?branch=develop)

####Master branch build status:
![](https://github.com/lnguyenviseo/cisum.svg?branch=master)
