language: objective-c
osx_image: xcode8.3

# branches:
#  only:
#  - develop
#  - travis-setup

xcode_project: CISum.xcodeproj        #can also use xcode_workspace
xcode_scheme: CISum                   #test scheme
xcode_sdk: iphonesimulator10.3

# script:
#   - xcodebuild clean test -project CISum.xcodeproj -scheme CISum -destination "platform=iOS Simulator,name=iPhone 6s,OS=9.0" | xcpretty
#   - xcodebuild clean test -project CISum.xcodeproj -scheme CISum -destination "platform=iOS Simulator,name=iPhone 6s,OS=10.3" | xcpretty

#### Develop branch build status:
# [![Develop branch build status](https://travis-ci.org/lnguyenviseo/cisum.svg?branch=travis-setup)](https://travis-ci.org/lnguyenviseo/cisum)
