language: objective-c
osx_image: xcode8

# branches:
#  only:
#  - develop
#  - travis-setup

xcode_project: CISum.xcodeproj        #can also use xcode_workspace
xcode_scheme: CISum                   #test scheme
xcode_sdk: iphonesimulator9.3

script:
  - xcodebuild -project CISum.xcodeproj -scheme CISum -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6S,OS=10.3" clean test build | xcpretty

### Develop branch build status:
# [![Develop branch build status](https://travis-ci.org/lnguyenviseo/cisum.svg?branch=travis-setup)](https://travis-ci.org/lnguyenviseo/cisum)
