language: objective-c
osx_image: xcode8.3.2

# branches:
#  only:
#  - develop
#  - travis-setup

xcode_project: CISum.xcodeproj        #can also use xcode_workspace
xcode_scheme: CISum                   #test scheme
xcode_sdk: iphonesimulator9.3

script:
  — xcodebuild -workspace CISum.xcworkspace -scheme CISum -sdk iphonesimulator -destination “platform=iOS Simulator,name=iPhone 6S,OS=9.3” test | xcpretty

####Develop branch build status:
# ![](https://travis-ci.org/lnguyenviseo/cisum.svg?branch=develop)
